### ISSUE TITLE
Battery Icon & Webcam

### ISSUE THREAD

**Issue by Rixxx-git** [Joaotcs/Hackintosh-Elitebook-8x0-g5#3]
Thanks for your EFI update, but the Battery still doesn't show in my menu bar and settings. Does it work for you?

Also: You write in your description, that the Camera is working. Does the Webcam work for you? 🙂

**Comment by Joaotcs** [comment]
Webcam only works if you are lucky (there are different models). You it doesn't work out of the box, you can forget it.
Are you sure you are running the latest bios? Please reset settings. 
And yes, battery is working just fine.

**Comment by Rixxx-git** [comment]
Strange. Battery was working fine with Kezincers EFI. But I don't know where the difference is to yours.
Do you have a documentation of all the necessary BIOS settings?

**Comment by Rixxx-git** [comment]
My BIOS Settings:

![IMG_0117](https://user-images.githubusercontent.com/51874661/101213388-9940c180-367a-11eb-96af-5783221e9aa6.jpg)
![IMG_0118](https://user-images.githubusercontent.com/51874661/101213395-9b0a8500-367a-11eb-9cd2-a86728185d5c.jpg)
![IMG_0119](https://user-images.githubusercontent.com/51874661/101213407-9fcf3900-367a-11eb-88c0-476569725511.jpg)
![IMG_0120](https://user-images.githubusercontent.com/51874661/101213410-a1006600-367a-11eb-9028-54d2e96164c4.jpg)
![IMG_0121](https://user-images.githubusercontent.com/51874661/101213412-a2ca2980-367a-11eb-82b6-248b54d593a7.jpg)
![IMG_0123](https://user-images.githubusercontent.com/51874661/101213415-a362c000-367a-11eb-852c-6629b14a4189.jpg)
![IMG_0124](https://user-images.githubusercontent.com/51874661/101213418-a493ed00-367a-11eb-88c3-e703a4c481d9.jpg)
![IMG_0125](https://user-images.githubusercontent.com/51874661/101213422-a5c51a00-367a-11eb-804a-fa899ac55080.jpg)
![IMG_0126](https://user-images.githubusercontent.com/51874661/101213425-a6f64700-367a-11eb-94b1-d4fd3992dd46.jpg)
![IMG_0127](https://user-images.githubusercontent.com/51874661/101213430-a8277400-367a-11eb-84b1-e6ffbcff0885.jpg)
![IMG_0128](https://user-images.githubusercontent.com/51874661/101213436-a958a100-367a-11eb-8b9d-5c03a0fa11ee.jpg)
![IMG_0129](https://user-images.githubusercontent.com/51874661/101213438-aa89ce00-367a-11eb-82ab-6452e7430779.jpg)

**Comment by Joaotcs** [comment]
It seems that settings are okay. 
My efi doesn't change battery related settings.

**Comment by Joaotcs** [comment]
Just make sure that my ssdt batt is the same as kecinzer (I might have made mistake at upload ut I don't think I did that)

**Comment by Rixxx-git** [comment]
Tried the ssdt batt from kecinzer. Still no battery icon. I don't have to change anything about config.plist when I use his ssdt batt file right?

**Comment by Joaotcs** [comment]
are you sure you have activated to show battery percentage on Big sur?
It should be working m8. I have tried this efi, and it is working...

**Comment by Rixxx-git** [comment]
Sure I have that! 😄

![Screenshot 2020-12-05 at 10 04 08](https://user-images.githubusercontent.com/51874661/101238548-43ebcb00-36e1-11eb-991e-724051b83a45.jpg)

**Comment by Rixxx-git** [comment]
Changed to the EFI from @kecinzer and got the battery icon back. Don't know where the difference of your two EFI setups is.

**Comment by Joaotcs** [comment]
Very strange as In mine it's working xD.
I will investigate that. The only thing I can recall is rtc fixe but shouldn't cause this bugs..

**Comment by Rixxx-git** [comment]
Really strange. 😄
What do you think is better about your EFI setup compared to the one from kecinzer in the daily use of the laptop?

**Comment by Joaotcs** [comment]
Sorry, my mistake!!! I forgot to update other battery related stuff. Please replace the config.plist now!

Well, the difference are in my README. plus, "less security option" - easier to use kext updater app and so on.

**Comment by Joaotcs** [comment]
Small differences only, the core is exactly the same...

**Comment by Rixxx-git** [comment]
Thanks for the update! :)
So there are no performance differences, right? No longer battery live or something like that?

**Comment by Joaotcs** [comment]
It should be not worse (the same).
