### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by Rixxx-git** [Joaotcs/Hackintosh-Elitebook-8x0-g5#4]
How do I install Windows 10 for dual boot? I used Parallels Desktop but since the Big Sur update it has network problems.

Thanks!

**Comment by Joaotcs** [comment]
I have dual windows and able to use parallels desktop with that partition. So I use my real windows partition whenever I want.

First, you should back up your EFI partition in a FAT32 formatted pen drive.
Second, you need a partition with free space (recommend at least 80gb for windows), you use that partition to install windows 10 from USB bootable drive.
Third, you will probably lose the boot menu to macintosh, you then, on windows, have to use cmd to open diskutil
then you select disk 0, then list volume, then you select the efi volume, and you write "assign letter X". You won't be able to open EFI partition on normal explorer. BUT, you are able to open it with the free app: "Explorer++" (you need to open it as admin). and you copy your efi backup to the efi partition of your laptop. If you have a folder called WINDOWS inside EFI folder, please backup that, and you should copy this to your new EFI folder also.

You should be able to boot to opencanopy, if not, you use F10 on laptop start, select efi partition and boot opencanopy. then you clean NVRAM, and you should be good to go, selecting windows 10 or macintosh on laptop start.

**Comment by Joaotcs** [comment]
You can then install parallels to boot your Windows 10 "bootcamp" so you can use it as a virtual machine inside macintosh also.

**Comment by Rixxx-git** [comment]
thanks!
